---
config:
  layout: dagre
---
flowchart TD
 subgraph s1["Resume/Cover Letter<br/>Tailoring Orchestra"]
        START --> E1["Job Positions Found"]
        E1 --> SO1["Input and Data Preparation"]
        SO1 --> IN1["Input Data"]
        IN1 --> SO2["JD Matching Orchestra"]
        SO2 --> OUT3["Selected Parsed JDs + Match and Skills Gap Analysis"]
        OUT3 --> SO3["Resume Writing Orchestra"]
        OUT3 --> SO4["Cover Letter Writing Orchestra"]
        SO3 --> OUT5["Resume Release Candidates"]
        SO4 --> OUT6["Cover Letter Release Candidates"]
        OUT5 --> SO5["Ideal Length Fitting Orchestra"]
        OUT6 --> SO6["Ideal Length Fitting Orchestra"]
        SO5 --> OUT1["Resume Release Version"]
        SO6 --> OUT2["Cover Letter Release Version"]
        OUT1 --> FINAL_WAIT["Wait"]
        OUT2 --> FINAL_WAIT
        FINAL_WAIT --> STOP

        %% Internal relationships within s1

        START@{ shape: start}
        E1@{ shape: event}
        IN1@{ shape: docs}
        SO1@{ shape: procs}
        SO2@{ shape: procs}
        SO3@{ shape: procs}
        SO4@{ shape: procs}
        SO5@{ shape: procs}
        SO6@{ shape: procs}
        OUT1@{ shape: tag-doc}
        OUT2@{ shape: tag-doc}
        IN1@{ shape: docs}
        OUT3@{ shape: docs}
        OUT5@{ shape: docs}
        OUT6@{ shape: docs}
        FINAL_WAIT@{ shape: stadium}
        STOP@{ shape: stop}
        E1:::EVENT
        IN1:::INPUT
        SO1:::SUBORCHESTRA
        SO2:::SUBORCHESTRA
        SO3:::SUBORCHESTRA
        SO4:::SUBORCHESTRA
        SO5:::SUBORCHESTRA
        SO6:::SUBORCHESTRA
        OUT1:::OUTPUT
        OUT2:::OUTPUT
        IN1:::OUTPUT
        OUT3:::OUTPUT
        OUT5:::OUTPUT
        OUT6:::OUTPUT
        FINAL_WAIT:::WAIT
  end
     s1:::ORCHESTRA

    classDef ORCHESTRA stroke-width:2px, stroke-dasharray:none, stroke:#D50000,fill:transparent, color:#D50000
    classDef SUBORCHESTRA stroke-width:2px, stroke-dasharray:none, stroke:#2962FF,fill:FFE0B2, color:#FFFFFF
    classDef INPUT stroke-width:2px, stroke-dasharray:none, fill:#e6ffe6, color:#000000
    classDef EVENT stroke-width:2px, stroke-dasharray:none, fill:#BBDEFB, color:#000000
    classDef RESEARCH stroke-width:2px, stroke-dasharray:none, fill:#FFF9C4, color:#000000
    classDef AGENT stroke-width:2px, stroke-dasharray:none, fill:#FFE0B2, color:#000000
    classDef OUTPUT stroke-width:2px, stroke-dasharray:none, fill:#C8E6C9, color:#000000
    classDef WAIT stroke-width:2px, stroke-dasharray:none, fill:#FFB74D, stroke:#F57C00, color:#000000
